name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install apt_dependencies
      run: sudo apt install python3 grub-pc
    # - name: configure
    #   run: ./configure
    - name: clone i686-elf-tools
      run: git clone https://github.com/lordmilko/i686-elf-tools
    - name: build i686-elf-tools
      run: cd i686-elf-tools && ./i686-elf-tools.sh linux
    - name: build
      run: ./build
    - name: verify
      run: grub-file --is-x86-multiboot bin/paranoia.bin